# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-06 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('p_username', models.CharField(max_length=100)),
                ('p_first_name', models.CharField(max_length=100)),
                ('p_last_name', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=32)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=48)),
                ('phone', models.CharField(default=0, max_length=15)),
                ('sex', models.CharField(max_length=15)),
                ('preferred_hospital', models.CharField(max_length=50)),
                ('usertype', models.CharField(default='patient', max_length=8)),
                ('primary_physician', models.CharField(max_length=50)),
                ('last_physical', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAdmins', models.IntegerField()),
                ('totalDoctors', models.IntegerField()),
                ('totalNurses', models.IntegerField()),
                ('totalPatients', models.IntegerField()),
                ('successfulLogins', models.IntegerField()),
                ('failedLogins', models.IntegerField()),
                ('appointmentsCreated', models.IntegerField()),
                ('medicationsPrescribed', models.IntegerField()),
                ('testsConducted', models.IntegerField()),
                ('messagesSent', models.IntegerField()),
                ('notificationsReceived', models.IntegerField()),
                ('patientsAdmitted', models.IntegerField()),
                ('oldestUser', models.CharField(max_length=50)),
            ],
        ),
    ]
